foods = ("rice", "beans", "rice", "yam", "rice", "beans")
print(foods.count("rice"))
animals = ("dog", "cat", "dog", "bird", "cat", "dog")
print(animals.index("dog"))
print(animals.count("cat"))
print(animals.index("bird"))
cities = ("abia", "imo", "enugu", "anambra", "ebonyi")
print(cities[0])
print(cities[4])
print(cities[2])
print(cities[2:4])
numbers = (9, 3, 5, 9, 3, 7, 9,)
print(numbers.count(9))
print(numbers.index(9))
